# Generated by Django 6.1.1 on 2026-09-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_size_kw', models.DecimalField(decimal_places=2, help_text='Installed capacity of the solar system, in kW.', max_digits=6)),
                ('panel_tilt_deg', models.DecimalField(decimal_places=1, help_text='Panel tilt angle in degrees from horizontal.', max_digits=4)),
                ('city', models.CharField(choices=[('manila', 'Manila'), ('quezon_city', 'Quezon City'), ('cebu_city', 'Cebu City'), ('davao_city', 'Davao City'), ('iloilo_city', 'Iloilo City'), ('baguio_city', 'Baguio City'), ('cagayan_de_oro', 'Cagayan de Oro'), ('zamboanga_city', 'Zamboanga City'), ('bacolod_city', 'Bacolod City'), ('general_santos', 'General Santos')], help_text='Philippine city/province used to look up irradiation & weather features.', max_length=64)),
                ('predicted_daily_yield_kwh', models.FloatField(blank=True, null=True)),
                ('estimated_monthly_php_savings', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
