# Generated by Django 6.1.1 on 2026-09-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityUtilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('manila', 'Manila'), ('quezon_city', 'Quezon City'), ('cebu_city', 'Cebu City'), ('davao_city', 'Davao City'), ('iloilo_city', 'Iloilo City'), ('baguio_city', 'Baguio City'), ('cagayan_de_oro', 'Cagayan de Oro'), ('zamboanga_city', 'Zamboanga City'), ('bacolod_city', 'Bacolod City'), ('general_santos', 'General Santos')], max_length=64, unique=True)),
                ('utility_name', models.CharField(max_length=64)),
                ('electricity_rate_php_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('optimal_tilt_deg', models.FloatField(default=10.0)),
                ('rate_is_estimated', models.BooleanField(default=False, help_text='True if no city-specific rate was found and a national-average default was used.')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.AddField(
            model_name='estimationrecord',
            name='electricity_rate_php_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Rate actually used for this estimate's PHP savings figure.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='estimationrecord',
            name='month_used',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='estimationrecord',
            name='predicted_capacity_factor',
            field=models.FloatField(blank=True, help_text='Raw model output before scaling by system_size_kw -- useful for QA/Day 7.', null=True),
        ),
        migrations.CreateModel(
            name='CityClimateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('manila', 'Manila'), ('quezon_city', 'Quezon City'), ('cebu_city', 'Cebu City'), ('davao_city', 'Davao City'), ('iloilo_city', 'Iloilo City'), ('baguio_city', 'Baguio City'), ('cagayan_de_oro', 'Cagayan de Oro'), ('zamboanga_city', 'Zamboanga City'), ('bacolod_city', 'Bacolod City'), ('general_santos', 'General Santos')], max_length=64)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('avg_peak_sun_hours', models.FloatField(help_text='Equivalent daily solar irradiation, kWh/m^2/day.')),
                ('avg_ambient_temp_c', models.FloatField(help_text='Typical ambient temperature for the month, °C.')),
                ('is_estimated', models.BooleanField(default=False, help_text='True if this row is interpolated/approximated rather than directly sourced.')),
            ],
            options={
                'ordering': ['city', 'month'],
                'unique_together': {('city', 'month')},
            },
        ),
    ]
