# Generated by Django 6.1.1 on 2026-09-11 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_cityutilityprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationrecord',
            name='panel_tilt_deg',
            field=models.DecimalField(decimal_places=1, help_text='Panel tilt angle in degrees from horizontal.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='estimationrecord',
            name='system_size_kw',
            field=models.DecimalField(decimal_places=2, help_text='Installed capacity of the solar system, in kW.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
